# Generated by Django 3.2.15 on 2022-11-06 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderproduct_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='count',
            new_name='quantity',
        ),
    ]
