# Generated by Django 3.2.15 on 2022-11-15 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='price_fixed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
