# Generated by Django 3.2.15 on 2022-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20221115_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Raw'), ('PR', 'Processed'), ('DE', 'Delivery'), ('CO', 'Complete')], default='RW', max_length=2),
        ),
    ]
