# Generated by Django 3.2.15 on 2022-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Необработанный'), ('PR', 'В ресторане'), ('DE', 'В доставке'), ('CO', 'Завершен')], db_index=True, default='RW', max_length=2),
        ),
    ]
