# Generated by Django 3.2.15 on 2023-01-10 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_order_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='price_fixed',
            new_name='fixed_price',
        ),
    ]
