# Generated by Django 3.2 on 2023-01-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0066_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_method',
        ),
    ]
