# Generated by Django 3.2.15 on 2023-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True, verbose_name='Долгота'),
        ),
    ]
