# Generated by Django 3.2.15 on 2022-11-08 20:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_rename_count_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='order',
            managers=[
                ('with_price', django.db.models.manager.Manager()),
            ],
        ),
    ]
