# Generated by Django 3.2.15 on 2022-11-15 18:54

from django.db import migrations


def set_order_products_price(apps, schema_editor):
    OrderProduct = apps.get_model('foodcartapp', 'OrderProduct')

    for product in OrderProduct.objects.iterator():
        product.price_fixed = product.product.price
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_orderproduct_price_fixed'),
    ]

    operations = [
        migrations.RunPython(set_order_products_price)
    ]
