# Generated by Django 3.2.15 on 2022-11-16 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20221116_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CS', 'Наличные'), ('EP', 'Электронная оплата')], db_index=True, max_length=2, null=True),
        ),
    ]
