# Generated by Django 3.2.15 on 2023-01-10 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_auto_20230111_0239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='performing_restaurant',
        ),
    ]
