# Generated by Django 3.2.15 on 2023-01-17 14:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_auto_20230111_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('CS', 'Наличные'), ('EP', 'Электронная оплата')], db_index=True, max_length=2, null=True, verbose_name='способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RW', 'Необработанный'), ('PR', 'В ресторане'), ('DE', 'В доставке'), ('CO', 'Завершен')], db_index=True, default='RW', max_length=2, verbose_name='статус заказа'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='fixed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='фиксированная стоимость'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество'),
        ),
    ]
