# Generated by Django 3.2 on 2023-01-20 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0064_alter_order_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_fulfilling_restaurant',
            new_name='fulfilling_restaurant',
        ),
    ]
